<?php

namespace ContainerKZukz4R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBalanceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BalanceController' shared autowired service.
     *
     * @return \App\Controller\BalanceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/BalanceController.php';

        return $container->services['App\\Controller\\BalanceController'] = new \App\Controller\BalanceController();
    }
}
