<?php

namespace ContainerVAlEqxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoryMethodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\HistoryMethod' shared autowired service.
     *
     * @return \App\Services\HistoryMethod
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/Domain/JsonRpcMethodInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/HistoryMethod.php';

        return $container->privates['App\\Services\\HistoryMethod'] = new \App\Services\HistoryMethod();
    }
}
