<?php

namespace ContainerVAlEqxv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonRpcHttpServer_MethodResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'json_rpc_http_server.method_resolver' shared service.
     *
     * @return \Yoanm\SymfonyJsonRpcHttpServer\Resolver\MethodResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/Domain/JsonRpcMethodResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/symfony-jsonrpc-http-server/src/Resolver/MethodResolver.php';

        return $container->services['json_rpc_http_server.method_resolver'] = new \Yoanm\SymfonyJsonRpcHttpServer\Resolver\MethodResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'balance.history' => ['privates', 'App\\Services\\HistoryMethod', 'getHistoryMethodService', true],
            'balance.userBalance' => ['privates', 'App\\Services\\UserBalanceMethod', 'getUserBalanceMethodService', true],
        ], [
            'balance.history' => '?',
            'balance.userBalance' => '?',
        ]));
    }
}
