<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKZukz4R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKZukz4R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKZukz4R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKZukz4R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKZukz4R\App_KernelDevDebugContainer([
    'container.build_hash' => 'KZukz4R',
    'container.build_id' => '78093acc',
    'container.build_time' => 1619526025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKZukz4R');
