<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_balance_getuserbalance' => [[], ['_controller' => 'App\\Controller\\BalanceController::getUserBalanceAction'], [], [['text', '/balance/user-balance']], [], []],
    'app_balance_getuserhistory' => [[], ['_controller' => 'App\\Controller\\BalanceController::getUserHistoryAction'], [], [['text', '/balance/user-balance']], [], []],
];
