<?php

namespace ContainerXRE6oOT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonRpcServerSdk_Infra_EndpointService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'json_rpc_server_sdk.infra.endpoint' shared service.
     *
     * @return \Yoanm\JsonRpcServer\Infra\Endpoint\JsonRpcEndpoint
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Dispatcher/JsonRpcServerDispatcherAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/Infra/Endpoint/JsonRpcEndpoint.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Serialization/JsonRpcCallSerializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Serialization/JsonRpcCallDenormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Serialization/JsonRpcRequestDenormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Serialization/JsonRpcCallResponseNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Serialization/JsonRpcResponseNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Handler/JsonRpcRequestHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Creator/ResponseCreator.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/App/Handler/ExceptionHandler.php';

        $a = new \Yoanm\JsonRpcServer\App\Creator\ResponseCreator();

        $b = new \Yoanm\JsonRpcServer\App\Handler\JsonRpcRequestHandler(($container->services['json_rpc_http_server.method_resolver'] ?? $container->load('getJsonRpcHttpServer_MethodResolverService')), $a);

        $c = ($container->services['json_rpc_http_server.dispatcher.server'] ?? $container->load('getJsonRpcHttpServer_Dispatcher_ServerService'));

        $b->setJsonRpcServerDispatcher($c);
        $b->setMethodParamsValidator(($container->services['json_rpc_params_validator_sdk.validator'] ?? $container->load('getJsonRpcParamsValidatorSdk_ValidatorService')));
        $d = new \Yoanm\JsonRpcServer\App\Handler\ExceptionHandler($a);
        $d->setJsonRpcServerDispatcher($c);

        $container->services['json_rpc_server_sdk.infra.endpoint'] = $instance = new \Yoanm\JsonRpcServer\Infra\Endpoint\JsonRpcEndpoint(new \Yoanm\JsonRpcServer\App\Serialization\JsonRpcCallSerializer(new \Yoanm\JsonRpcServer\App\Serialization\JsonRpcCallDenormalizer(new \Yoanm\JsonRpcServer\App\Serialization\JsonRpcRequestDenormalizer()), new \Yoanm\JsonRpcServer\App\Serialization\JsonRpcCallResponseNormalizer(new \Yoanm\JsonRpcServer\App\Serialization\JsonRpcResponseNormalizer())), $b, $d);

        $instance->setJsonRpcServerDispatcher($c);

        return $instance;
    }
}
