<?php

namespace ContainerXRE6oOT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserBalanceMethodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\UserBalanceMethod' shared autowired service.
     *
     * @return \App\Services\UserBalanceMethod
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-server-sdk/src/Domain/JsonRpcMethodInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/yoanm/jsonrpc-params-symfony-validator-sdk/src/Domain/MethodWithValidatedParamsInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/UserBalanceMethod.php';

        return $container->privates['App\\Services\\UserBalanceMethod'] = new \App\Services\UserBalanceMethod(($container->privates['App\\Repository\\BalanceHistoryRepository'] ?? $container->load('getBalanceHistoryRepositoryService')));
    }
}
